name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install Hugo
      - name: Install Hugo
        run: |
          sudo apt-get update
          sudo apt-get install -y hugo

      # Build Hugo site
      - name: Build Hugo Site
        run: hugo -D --minify

      # Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_WICKET_GATE_BLOG }}
          channelId: live
          projectId: wicket-gate-blog
